[package]
name = "kosmonaut"
version = "0.1.0"
authors = ["Tyler Wilcock <twilco.o@protonmail.com>"]
edition = "2018"

[dependencies]
accountable-refcell = { path = "../accountable-refcell" }
app_units = "0.7.1"
cssparser = "0.27"
clap = "2.33.0"
font-kit = { git = "https://github.com/twilco/font-kit" }
gl = { path = "crates/gl" }
glutin = "0.24"
html5ever = "0.25.1"
image = "0.23"
matches = "0.1.8"
pathfinder_geometry = "0.5.1"
rand = "0.7.3"
selectors = "0.22.0"
smallbitvec = "2.5.0"
strum = "0.18.0"
strum_macros = "0.18.0"
tempdir = "0.3.7"
derive_builder = "0.9.0"

[dev-dependencies]
insta = "0.16"

[features]
gl_debug = ["gl/debug"]
